export * as LogoutIcon from './Logout.svg';
export * as rejectLogo from './kycReject.svg'
// export * as horecaHLogo from './horecaHLogo.png'
export * as face from './face.svg'
export * as kycSucess from './kycSuccess.png'
export * as kycVerificationLogo from './kycVerification.svg'
export * as PrimaryLogo from './horeca.svg'
export * as delhi from './delhi.svg'
export * as mumbai from './mumbai.svg'
export * as banglore from './banglore.svg'
export * as kolkata from './kolkata.svg'
export * as hydrabad from './hydrabad.svg'
export * as addBanner from './addBanner.svg'