export { default as withPosts } from "./list";
export { default as withPost } from "./item";
export { default as withCreatePost } from "./create";
export { default as withUpdatePost } from "./update";
export { default as withDeletePost } from "./delete";
export { default as withGetOne } from "./getOne";
export { default as withInsert } from "./updateOne";
export { default as withGetUser } from "./getUser";
export { default as withOTP } from "./otp";
